pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t myflaskapp .'
            }
        }

        stage('Test') {
            steps {
                sh 'pytest || echo "Tests failed"'
            }
        }

        stage('Push') {
            steps {
                sh 'echo "Pushing to DockerHub..."'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 myflaskapp'
            }
        }
    }
}
